{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'svg-model' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
    noarch: python
    number: 0
    script:
        # Install source directory as Python package.
        - python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python >=3.6
        - lxml
        - pandas
        - funcsigs
        - pandas
        - pint
        - pymunk >=6.0.0
        - pyparsing
        - svgwrite
        - path-helpers

    run:
        - python >=3.6
        - lxml
        - pandas
        - funcsigs
        - pandas
        - pint
        - pymunk >=6.0.0
        - pyparsing
        - svgwrite
        - path-helpers

test:
    imports:
        - svg_model

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: LGPLv2.1
  summary: A Python module for parsing an SVG file to a group of paths.

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
#  git_url: ../
  path: ..